// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package efm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/mwitkow/go-proto-validators"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty" db:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" db:"xxx___no_unkeyed_literal"`
	XXX_unrecognized     []byte   `json:"-" db:"xxx___unrecognized"`
	XXX_sizecache        int32    `json:"-" db:"xxx___sizecache"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_bb92b7a243de0cda, []int{0}
}
func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (dst *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(dst, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

func (m *TestRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TestReply struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty" db:"msg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" db:"xxx___no_unkeyed_literal"`
	XXX_unrecognized     []byte   `json:"-" db:"xxx___unrecognized"`
	XXX_sizecache        int32    `json:"-" db:"xxx___sizecache"`
}

func (m *TestReply) Reset()         { *m = TestReply{} }
func (m *TestReply) String() string { return proto.CompactTextString(m) }
func (*TestReply) ProtoMessage()    {}
func (*TestReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_bb92b7a243de0cda, []int{1}
}
func (m *TestReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReply.Unmarshal(m, b)
}
func (m *TestReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReply.Marshal(b, m, deterministic)
}
func (dst *TestReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReply.Merge(dst, src)
}
func (m *TestReply) XXX_Size() int {
	return xxx_messageInfo_TestReply.Size(m)
}
func (m *TestReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReply.DiscardUnknown(m)
}

var xxx_messageInfo_TestReply proto.InternalMessageInfo

func (m *TestReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "efm.TestRequest")
	proto.RegisterType((*TestReply)(nil), "efm.TestReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	Ping(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn `db:"cc"`
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Ping(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error) {
	out := new(TestReply)
	err := grpc.Invoke(ctx, "/efm.Greeter/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	Ping(context.Context, *TestRequest) (*TestReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/efm.Greeter/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Ping(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "efm.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Greeter_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_greeter_bb92b7a243de0cda) }

var fileDescriptor_greeter_bb92b7a243de0cda = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0x87, 0xd9, 0x3f, 0xa8, 0x1b, 0x51, 0x4a, 0x4e, 0x4b, 0x55, 0xd4, 0x9e, 0xbc, 0x6c, 0x83,
	0x0a, 0x1e, 0xbc, 0x8b, 0x57, 0x59, 0x7c, 0x81, 0x54, 0xa7, 0x31, 0xd8, 0xc9, 0xc4, 0x66, 0xba,
	0x4b, 0xaf, 0xbe, 0x82, 0x8f, 0xe6, 0x2b, 0xf8, 0x20, 0x62, 0x52, 0xa4, 0xec, 0xed, 0x37, 0xf3,
	0x7d, 0x33, 0xcc, 0x88, 0x23, 0xd3, 0x02, 0x30, 0xb4, 0xa5, 0x6f, 0x89, 0x49, 0xce, 0xa0, 0xc6,
	0xfc, 0xd4, 0x10, 0x99, 0x06, 0x94, 0xf6, 0x56, 0x69, 0xe7, 0x88, 0x35, 0x5b, 0x72, 0x21, 0x29,
	0xf9, 0xc9, 0x40, 0x63, 0x55, 0x75, 0xb5, 0x02, 0xf4, 0xdc, 0x0f, 0xf0, 0x7c, 0x17, 0xb2, 0x45,
	0x08, 0xac, 0xd1, 0x0f, 0xc2, 0x9d, 0xb1, 0xfc, 0xd6, 0x55, 0xe5, 0x0b, 0xa1, 0xc2, 0xad, 0xe5,
	0x77, 0xda, 0x2a, 0x43, 0xab, 0x08, 0x57, 0x1b, 0xdd, 0xd8, 0x57, 0xcd, 0xd4, 0x06, 0xf5, 0x1f,
	0xd3, 0x5c, 0x71, 0x29, 0x0e, 0x9f, 0x21, 0xf0, 0x1a, 0x3e, 0x3a, 0x08, 0x2c, 0xa5, 0x98, 0x3b,
	0x8d, 0xb0, 0x9c, 0x5c, 0x4c, 0xae, 0x16, 0xeb, 0x98, 0x8b, 0x33, 0xb1, 0x48, 0x8a, 0x6f, 0x7a,
	0x99, 0x89, 0x19, 0x06, 0xb3, 0x9c, 0x46, 0xfe, 0x17, 0x6f, 0x1e, 0xc4, 0xfe, 0x63, 0xfa, 0x55,
	0xde, 0x8b, 0xf9, 0x93, 0x75, 0x46, 0x66, 0x25, 0xd4, 0x58, 0x8e, 0xf6, 0xe6, 0xc7, 0xa3, 0x8e,
	0x6f, 0xfa, 0x22, 0xfb, 0xfc, 0xfe, 0xf9, 0x9a, 0x0a, 0x79, 0xa0, 0x36, 0xd7, 0xca, 0x5b, 0x67,
	0xaa, 0xbd, 0x78, 0xcf, 0xed, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x82, 0x8a, 0x01, 0x39,
	0x01, 0x00, 0x00,
}
