// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: greeter.proto

/*
Package efm is a generated protocol buffer package.

It is generated from these files:
	greeter.proto

It has these top-level messages:
	TestRequest
	TestReply
*/
package efm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *TestRequest) Validate() error {
	return nil
}
func (this *TestReply) Validate() error {
	return nil
}
